package com.example.instachat.services.room_sync

enum class SyncTables(tableName: String) {
    POSTS("POSTS"),
    USERS("USERS"),
    COMMENTS("COMMENTS"),
    NEW_POST("NEW_POST"),
    NEW_USER("NEW_USER"),
    USERS_UPDATE_FOLLOWING("USERS_UPDATE_FOLLOWING"),
    USERS_UPDATE_INTERESTED_USERS("USERS_UPDATE_INTERESTED_USERS"),
    USERS_UPDATE_REQUESTED_INTERESTED_USERS("USERS_UPDATE_REQUESTED_INTERESTED_USERS"),
    ADD_INTERESTED_LIST("ADD_INTERESTED_LIST"),
    ADD_REQUEST_INTERESTED_LIST("ADD_REQUEST_INTERESTED_LIST")
}